### ISSUE TITLE
Build requirements for Java 11

### ISSUE THREAD

**Issue by hz-lschick** [project-a/mondrian-server#3]
When running the project with Java 11 (LTS), it will crash with `Type javax.xml.bind.JAXBContext not present`

Here a guide how to fix this: https://crunchify.com/java-11-and-javax-xml-bind-jaxbcontext/

**Comment by gathineou** [comment]
@hz-lschick thanks for the how-to-fix guide. I created a PR for this: https://github.com/project-a/mondrian-server/pull/4
